version: '3.9'

services:
  resolver:
    platform: linux/amd64
    build:
      context: src/functions/resolvers
      dockerfile: Dockerfile
      args:
        - GitHubToken=${GitHubToken:-""}
    container_name: resolver
    ports:
      - 9000:8080
    environment:
      - Environment=${Environment:-dev}
    logging:
      options:
        max-size: "10m"
        max-file: "5"

